Slight changes in dotprinter again
rise-lang/rise pull request #29
Opened 2020-02-14 08:04 UTC by bastianhagedorn

* adding colors
* highlight low-level mapSeq and reduceSeq

2020-02-14 10:20 UTC, Bastacyclop commented on src/main/scala/rise/core/dotPrinter.scala
> +        // keep for now: used as style in the paper
maybe precise which paper you are talking about in the code

2020-02-14 10:21 UTC, Bastacyclop requested changes
maybe you can address the small style issues?

2020-02-19 16:49 UTC, michel-steuwer submitted a review, later dismissed

2020-03-05 10:55 UTC, bastianhagedorn commented
all style issues have been addressed

2020-03-05 11:13 UTC, Bastacyclop submitted a review, later dismissed

2020-05-27 16:37 UTC, michel-steuwer approved these changes

2020-05-27 16:37 UTC, merged